name: Plumeria Scientific Libraries Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-darwin-m1:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      
      - name: Spack installations
        run: |
          git clone --depth=1 https://github.com/spack/spack.git
          . spack/share/spack/setup-env.sh
          spack compiler find
          spack env activate --dir spack-environments/darwin-m1
          spack install
      
      - name: Upload Spack build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plumeria-libraries-darwin-m1
          path: spack-environments/darwin-m1/.spack-env/view/
          retention-days: 90

  build-linux-aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      
      - name: Spack installations
        run: |
          git clone --depth=1 https://github.com/spack/spack.git
          . spack/share/spack/setup-env.sh
          spack compiler find
          spack env activate --dir spack-environments/linux-aarch64
          spack install
      
      - name: Upload Spack build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plumeria-libraries-linux-aarch64
          path: spack-environments/linux-aarch64/.spack-env/view/
          retention-days: 90
