name: Release

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [main]

env:
  VERSION: "0.1"

jobs:
  release:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Create new tag
        id: create-tag
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          TAG="${VERSION}-${TIMESTAMP}"
          
          git config user.name "Brandon Murakami"
          git config user.email "bmurakami@berkeley.edu"
          git tag "$TAG"
          git push origin "$TAG"
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          pattern: pluscilib-*
          path: ./artifacts/
          merge-multiple: false
          
      - name: Create archive packages
        run: |
          cd artifacts
          tar -czf pluscilib-darwin-m1.tar.gz -C pluscilib-darwin-m1 .
          tar -czf pluscilib-linux-aarch64.tar.gz -C pluscilib-linux-aarch64 .
          tar -czf pluscilib-linux-neoverse_v2.tar.gz -C pluscilib-linux-neoverse_v2 .
          tar -czf pluscilib-linux-x86_64.tar.gz -C pluscilib-linux-x86_64 .
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-tag.outputs.tag }}
          name: Release ${{ steps.create-tag.outputs.tag }}
          draft: false
          prerelease: true
          files: |
            artifacts/*.tar.gz
