name: Plumeria Scientific Libraries

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: pluscilib-*
          path: ./artifacts/
          merge-multiple: false
          
      - name: Create archive packages
        run: |
          cd artifacts
          tar -czf pluscilib-darwin-m1.tar.gz -C darwin-m1 .
          tar -czf pluscilib-linux-aarch64.tar.gz -C linux-aarch64 .
          tar -czf pluscilib-linux-neoverse_v2.tar.gz -C linux-neoverse_v2 .
          tar -czf pluscilib-linux-x86_64.tar.gz -C linux-x86_64 .
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: true
          files: |
            artifacts/*.tar.gz